### ISSUE TITLE
A bit of refactoring

### ISSUE THREAD

**Issue by vladkampov** [DrDezmond/testW#5]
Since we are on the issues resolving I want kindly ask you to pay some attention at the following component.
https://github.com/DrDezmond/testW/blob/TestW-Another-Changes/src/components/UserList/index.jsx
Could it be rewritten in a better way?

**Comment by DrDezmond** [comment]
@vladkampov hope i did what you asked for.

**Comment by vladkampov** [comment]
It's enough. Thanks 👍
